name: Docker Pipeline

on:
    workflow_run:
        workflows: ["Python application"]
        types: [completed]
        branches: ["main"]

jobs:
    build-docker-images:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3

              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/textrefine:latest
